org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# 当前目标使用 Minecraft 26.1.2 与 NeoForge 26.1.2.97。
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,27)
neoforge_version=26.1.2.97
neoforge_version_range=[26.1.2.97,)
loader_version_range=[4,)
xaeros_minimap_file_id=8042348
xaeros_minimap_version_range=[25.3.12,)

# 当前项目使用 NeoForge 内置的官方 Mojang 映射。
mod_id=eyes_of_waypoints
mod_name=Eyes of Waypoints
mod_license=All Rights Reserved
mod_version=1.2
mod_group_id=org.hp
mod_authors=HP
mod_description=Automatically create Xaero's Minimap waypoints from vanilla Eye of Ender targets.
