modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "eyes_of_waypoints.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "xaerominimap"
type = "required"
versionRange = "${xaeros_minimap_version_range}"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "cataclysm"
type = "required"
versionRange = "${lendercataclysm_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "legendary_monsters"
type = "required"
versionRange = "${legendary_monsters_version_range}"
ordering = "AFTER"
side = "BOTH"
